/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:271a92b9-7d79-4c43-b8eb-deaa7a47e758",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_DCBHxBh8T",
    "aws_user_pools_web_client_id": "5bcke3mbodpj2acjplc8j6krtp",
    "oauth": {
        "domain": "easyexpense2b95c079-2b95c079-prod.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://easy-expense-client.herokuapp.com/",
        "redirectSignOut": "https://easy-expense-client.herokuapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
